<?php

/**
 * This file is part of the "Forums" Extension for TYPO3 CMS.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 *
 * (c) 2022 Mark Weisgerber <mark.weisgerber@outlook.de>
 */

namespace Weisgerber\Forums\ViewHelpers;

use TYPO3\CMS\Extbase\Object\ObjectManagerInterface;
use TYPO3Fluid\Fluid\Core\Rendering\RenderingContextInterface;
use TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper;
use Weisgerber\Forums\Service\Configuration\ConfigurationService;

class RenderViewHelper extends AbstractViewHelper
{

    public function initializeArguments()
    {
        parent::initializeArguments();
        $this->registerArgument('style', 'string', 'The selected style', false, $this->getSettings()['css']['mode']);
    }

    public static function renderStatic(array $arguments, \Closure $renderChildrenClosure, RenderingContextInterface $renderingContext)
    {
        $arguments['partial'] .= '.'.$arguments['style'];
        return parent::renderStatic($arguments, $renderChildrenClosure, $renderingContext); // TODO: Change the autogenerated stub
    }

    /**
     * Liefert das TS der Extension
     * @return array
     */
    public function getSettings() {
        return $this->configurationService->getSettings();
    }
}
