<?php

/**
 * This file is part of the "Forums" Extension for TYPO3 CMS.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 *
 * (c) 2022 Mark Weisgerber <mark.weisgerber@outlook.de>
 */

namespace Weisgerber\Forums\ViewHelpers;

use TYPO3\CMS\Extbase\Configuration\ConfigurationManagerInterface;
use TYPO3\CMS\Extbase\Object\ObjectManagerInterface;
use TYPO3\CMS\Extbase\Utility\DebuggerUtility;
use TYPO3Fluid\Fluid\Core\Rendering\RenderingContextInterface;
use Weisgerber\Forums\Service\Configuration\ConfigurationService;

class RenderViewHelper extends \TYPO3\CMS\Fluid\ViewHelpers\RenderViewHelper
{
    /**
     * @var \TYPO3\CMS\Extbase\Object\ObjectManagerInterface
     */
    protected $objectManager;

    /**
     * @var \Datamints\DatamintsElearning\Services\Configuration\ConfigurationService
     */
    protected $configurationService;

    /**
     * @param \TYPO3\CMS\Extbase\Object\ObjectManagerInterface $objectManager
     * @param ConfigurationService $configurationService
     */
    public function __construct(ObjectManagerInterface $objectManager, ConfigurationService $configurationService) {
        $this->objectManager = $objectManager;
        $this->configurationService = $configurationService;
    }

    public function initializeArguments()
    {
        parent::initializeArguments();
        $this->registerArgument('style', 'string', 'The selected style', false, $this->getSettings()['css']['mode']);
    }

    public static function renderStatic(array $arguments, \Closure $renderChildrenClosure, RenderingContextInterface $renderingContext)
    {
        $arguments['partial'] .= '.'.$arguments['style'];
        return parent::renderStatic($arguments, $renderChildrenClosure, $renderingContext); // TODO: Change the autogenerated stub
    }

    /**
     * Liefert das TS der Extension
     * @return array
     */
    public function getSettings() {
        return $this->configurationService->getSettings();
    }
}
